name: CI
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - name: npm install, build, and test
        run: npm install
      - name: test + build
        run: |
          npm run lint
          npm run test
          npm run build
        env:
          CI: true
